site_name: cwtch

nav:
  - Описание: index.md
  - Установка: installation.md
  - Руководство пользователя:
    - Основы: user_guide/basic.md
    - Валидация: user_guide/validation.md
    - Передставления (view): user_guide/view.md
  - API справочник: api_reference.md

theme:
  language: ru
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: light blue
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition

plugins:
  - search
  - mkdocstrings

extra_css:
  - css/extra.css

extra:
  alternate:
  - link: ../en
    name: en - English
  - link: .
    name: ru - Русский

repo_url: https://github.com/levsh/cwtch
