site_name: cwtch

nav:
  - About: index.md
  - Installation: installation.md
  - User Guide: user_guide/basic.md
  - API Reference: api_reference.md

theme:
  language: en
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: light blue
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition

plugins:
  - search
  - mkdocstrings

extra_css:
  - css/extra.css

extra:
  alternate:
  - link: .
    name: en - English
  - link: ../ru
    name: ru - Русский

repo_url: https://github.com/levsh/cwtch
