site_name: cwtch

site_url: https://levsh.github.io/cwtch/

nav:
  - cwtch: index.md

theme:
  language: en
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: light blue
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          load_external_modules: true

extra_css:
  - css/extra.css

extra:
  alternate:
  - link: en
    name: en - English
  - link: ru
    name: ru - Русский

repo_url: https://github.com/levsh/cwtch
